@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}
@userEmailForTesting = jonata.marcelino83@gmail.com
@userPasswordForTesting = 123456
@userNameForTesting = Jonata Marcelino

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

# {
#   "email": "johny21@gmail.com",
#   "password": "123"
# }

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "João",
  "email": "joao@email.com",
  "password": "12356"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Jônata Marcelino",
  "email": "joao@email.com"
}

### Get user
# @name getUser
GET {{baseUrl}}/user/58344732-2d62-4e26-9ac3-52a54cab8499
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Get users
# @name getUsers
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
